name: Android CI - Build APK with Chinese Resources

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 详细资源验证
      - name: Validate Resources
        run: |
          echo "=== 验证资源文件 ==="
          echo "当前目录: $(pwd)"
          echo "资源目录结构:"
          find app/src/main/res -type d | grep "values" || echo "⚠️ 未找到values目录"
          
          CN_FILE="app/src/main/res/values-cn/strings.xml"
          if [ -f "$CN_FILE" ]; then
            echo "✅ 找到中文资源文件"
            echo "文件编码: $(file -bi "$CN_FILE")"
            echo "前5行内容:"
            head -n 5 "$CN_FILE"
          else
            echo "❌ 错误：找不到 $CN_FILE"
            echo "当前res目录内容:"
            ls -la app/src/main/res/
            exit 1
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 彻底清理环境
      - name: Clean environment
        run: |
          ./gradlew clean
          rm -rf ~/.gradle/caches/
          rm -rf app/build

      # 构建并验证
      - name: Build and Verify
        run: |
          echo "=== 开始构建 ==="
          ./gradlew assembleDebug --stacktrace --info
          
          echo "=== 检查APK内容 ==="
          APK_PATH=$(ls app/build/outputs/apk/debug/*.apk | head -1)
          
          echo "APK中的values目录:"
          unzip -l "$APK_PATH" | grep "values-" || echo "⚠️ 未找到values目录"
          
          echo "尝试提取中文资源:"
          if unzip -p "$APK_PATH" "res/values-cn/strings.xml" > /tmp/cn.xml; then
            echo "✅ 成功提取中文资源"
            echo "资源文件大小: $(wc -l < /tmp/cn.xml) 行"
          else
            echo "❌ 错误：无法提取中文资源"
            echo "APK完整内容:"
            unzip -l "$APK_PATH" | grep "res/"
            exit 1
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk
