name: Android CI - Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 安装 dos2unix 并修复 gradlew 权限（关键修复）
      - name: Fix gradlew permissions
        run: |
          # 安装 dos2unix（处理Windows换行符）
          sudo apt-get update && sudo apt-get install -y dos2unix
          
          # 转换换行符并设置权限
          dos2unix gradlew
          chmod +x gradlew
          
          # 验证权限
          ls -l gradlew | grep -e '-rwxr' || (echo "❌ gradlew 权限设置失败"; exit 1)

      # 3. 设置 JDK 环境
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      # 4. 构建前验证环境
      - name: Validate environment
        run: |
          ./gradlew --version || (echo "❌ gradlew 执行测试失败"; exit 1)

      # 5. 执行构建
      - name: Build APK
        run: |
          ./gradlew clean assembleDebug --stacktrace

      # 6. 检查中文资源
      - name: Verify Chinese resources
        run: |
          unzip -l app/build/outputs/apk/debug/*.apk | grep values-cn/strings.xml || \
            (echo "❌ 错误：APK中未找到中文资源"; exit 1)

      # 7. 上传产物
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apk-artifacts
          path: |
            app/build/outputs/apk/debug/*.apk
            app/build/reports/
          retention-days: 3
