name: Android CI - 构建含中文资源的APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      # 资源验证（修正中文路径）
      - name: 验证中英文资源
        run: |
          echo "=== 资源文件检查 ==="
          echo "项目结构:"
          find app/src/main/res -type d | grep "values"

          # 检查英文资源（必须存在）
          EN_FILE="app/src/main/res/values/strings.xml"
          if [ ! -f "$EN_FILE" ]; then
            echo "❌ 错误：缺少默认英文资源 $EN_FILE"
            exit 1
          fi

          # 检查中文资源（修正为zh）
          ZH_FILE="app/src/main/res/values-zh/strings.xml"
          if [ -f "$ZH_FILE" ]; then
            echo "✅ 找到中文资源文件"
            echo "文件编码: $(file -bi "$ZH_FILE")"
            echo "前5行示例:"
            head -n 5 "$ZH_FILE" | sed 's/^/    /'
          else
            echo "⚠️ 警告：未找到中文资源 $ZH_FILE"
          fi

      - name: 设置JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 清理构建环境
      - name: 清理环境
        run: |
          ./gradlew clean
          rm -rf ~/.gradle/caches/

      # 构建与验证
      - name: 构建APK并验证资源
        run: |
          echo "=== 开始构建Debug包 ==="
          ./gradlew assembleDebug --stacktrace

          echo "=== 检查APK内资源 ==="
          APK_PATH=$(ls app/build/outputs/apk/debug/*.apk | head -1)
          
          echo "1. 检查是否包含中文资源:"
          if unzip -l "$APK_PATH" | grep -q "values-zh"; then
            echo "✅ APK中包含中文资源"
          else
            echo "⚠️ 警告：APK中未检测到中文资源"
          fi

          echo "2. 资源文件完整列表:"
          unzip -l "$APK_PATH" | grep "res/values"

      - name: 上传APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk
